allowBuilds:
  core-js: true
  es5-ext: true
  is-hidden-file: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@babel/code-frame@8.0.6'
  - '@babel/core@8.0.6'
  - '@babel/generator@8.0.6'
  - '@babel/helper-compilation-targets@8.0.6'
  - '@babel/helper-globals@8.0.6'
  - '@babel/helper-string-parser@8.0.6'
  - '@babel/helper-validator-identifier@8.0.6'
  - '@babel/parser@8.0.6'
  - '@babel/traverse@8.0.6'
  - '@babel/types@8.0.6'
